[package]
name = "decision"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam-channel = "0.5"
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }
[lib]
path = "decision.rs"